language: python  # we need python, pip, clang-format, and g++.
python:
  - "3.6"
install:
  - pip install -r requirements-test.txt
script:
  - make concat-build
  - pytest test_integrate.py
# after_success:
#   - codecov
